http://localhost:3000/users

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "firstName": "Beverly",
    "lastName": "Crusher",
    "handle": "@doctor",
    "password": "notreal"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "handle": "@doctor",
    "password": "notreal"
}

###
http://localhost:3000/posts

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "src": "https://bulma.io/images/placeholders/1280x960.png",
    "alt": "The Doctor's post",
    "caption": "Lorem Ipsom",
    "time": "Mon Mar 22 2021 14:23:35 GMT-0400 (Eastern Daylight Time)",
    "user_handle": "@doctor"
}